all:
  hosts:
    inventory_test:
      ansible_host: 127.0.0.1

  children:

    ubuntu_repository:
      hosts:
        sea0020sdp01.frontedge.net:
          ansible_host: sea0020sdp01.frontedge.net
          patch_day: Mon
          patch_time: "01:00"
          reboot_time: "02:00"

    oracle_repository:
      hosts:
        sea0020sdp02.frontedge.net:
          ansible_host: sea0020sdp02.frontedge.net

    redhat_repository:
      hosts:
        sea0020sdp03.frontedge.net:
          ansible_host: sea0020sdp03.frontedge.net

    dns:
      hosts:
        webmin.frontedge.net:
          ansible_host: webmin.frontedge.net
        sea0020smg1.frontedge.net:
          ansible_host: sea0020smg1.frontedge.net
        sea0020smg2.frontedge.net:
          ansible_host: sea0020smg2.frontedge.net
        sea0020sns1.frontedge.net:
          ansible_host: sea0020sns1.frontedge.net

    mailrelay:
      hosts:
        sea0020smg3.frontedge.net:
          ansible_host: sea0020smg3.frontedge.net
