all:
  children:

    ubuntu_repository:
      hosts:
        sea0020sdp01.frontedge.net:
          patch_day: Mon
          patch_time: "01:00"
          reboot_time: "02:00"
      vars:
        patch_day: Mon
        patch_time: "01:00"
        reboot_day: Mon
        reboot_time: "02:00"

    oracle_repository:
      hosts:
        sea0020sdp02.frontedge.net: {}

    redhat_repository:
      hosts:
        sea0020sdp03.frontedge.net: {}

    suse_repository:
      hosts:
        inxs: {}

    dns:
      hosts:
        webmin.frontedge.net: {}
        sea0020smg1.frontedge.net: {}
        sea0020smg2.frontedge.net: {}
        sea0020sns1.frontedge.net: {}

    mailrelay:
      hosts:
        sea0020smg3.frontedge.net: {}

    iga:
      hosts:
        electric: {}
        lars: {}
        vegas: {}
        light: {}
        orchestra: {}

    confluence:
      hosts:
        powerwolf: {}
        dragonforce: {}

    nextcloud:
      hosts:
        newpil: {}
        broxpintnc01: {}
        broxpextnc01: {}
